import hashlib
import typing

import cdk_nag
import constructs
from aws_cdk import CfnTag, Tags, aws_ram, aws_ssm, custom_resources

from infra import constants


class BackendAppSharedSSMParameters(constructs.Construct):
    """Creates an SSM parameter that is shared with the spoke accounts.

    Creates a Resource Access Management (RAM) resource share which the onboarding process will then share with the spoke account.
    Method `add_shared_ssm_parameter` creates an advanced tier SSM parameter and associates it with the RAM resource share.

    Note, that spoke accounts can be in any region, which means that the stack that this resource is used in must be deployed in all
    VEW regions.

    """

    def __init__(
        self,
        scope: constructs.Construct,
        id: str,
        name: str,
    ):
        super().__init__(scope, id)

        self.__ssm_resource_share = aws_ram.CfnResourceShare(
            self,
            "SSMParameterResourceShare",
            name=name,
            allow_external_principals=False,
            permission_arns=["arn:aws:ram::aws:permission/AWSRAMDefaultPermissionSSMParameterReadOnly"],
            tags=[CfnTag(key=constants.RESOURCE_ACCESS_MANAGEMENT_TAG_NAME, value="true")],
        )

    def add_shared_ssm_parameter(self, parameter_name: str, string_value: str) -> typing.Self:

        ssm_param = aws_ssm.StringParameter(
            self,
            f"SSMParameter-{parameter_name}",
            string_value=string_value,
            parameter_name=parameter_name,
            tier=aws_ssm.ParameterTier.ADVANCED,
            type=aws_ssm.ParameterType.STRING,
        )

        Tags.of(ssm_param).add(constants.RESOURCE_ACCESS_MANAGEMENT_TAG_NAME, "true")

        id = f"ParameterShare#{parameter_name}"
        client_token = hashlib.sha256(id.encode("utf-8")).hexdigest()[:64]

        cs = custom_resources.AwsCustomResource(
            self,
            f"AssociateSSMParamWithShare-{parameter_name}",
            on_create=custom_resources.AwsSdkCall(
                service="ram",
                action="AssociateResourceShare",
                parameters={
                    "clientToken": client_token,
                    "resourceArns": [ssm_param.parameter_arn],
                    "resourceShareArn": self.__ssm_resource_share.attr_arn,
                },
                physical_resource_id=custom_resources.PhysicalResourceId.of(id),
            ),
            on_delete=custom_resources.AwsSdkCall(
                service="ram",
                action="DisassociateResourceShare",
                parameters={
                    "clientToken": client_token,
                    "resourceArns": [ssm_param.parameter_arn],
                    "resourceShareArn": self.__ssm_resource_share.attr_arn,
                },
                physical_resource_id=custom_resources.PhysicalResourceId.of(id),
            ),
            policy=custom_resources.AwsCustomResourcePolicy.from_sdk_calls(
                resources=[self.__ssm_resource_share.attr_arn]
            ),
        )

        cdk_nag.NagSuppressions.add_resource_suppressions(
            cs,
            suppressions=[
                cdk_nag.NagPackSuppression(
                    id="NIST.800.53.R4-IAMNoInlinePolicy",
                    reason="Autogenerated by CDK.",
                ),
                cdk_nag.NagPackSuppression(
                    id="NIST.800.53.R5-IAMNoInlinePolicy",
                    reason="Autogenerated by CDK.",
                ),
                cdk_nag.NagPackSuppression(
                    id="PCI.DSS.321-IAMNoInlinePolicy",
                    reason="Autogenerated by CDK.",
                ),
            ],
            apply_to_children=True,
        )
        return self
