import aws_cdk
import cdk_nag
import constructs
from aws_cdk import aws_backup, aws_dynamodb

from infra import config


class BackendAppStorage(constructs.Construct):
    def __init__(
        self,
        scope: constructs.Construct,
        id: str,
        app_config: config.AppConfig,
        table_name: str = "table",
        enable_ttl: bool = False,
        enable_streaming: bool = False,
        encryption_key=None,
    ) -> None:
        super().__init__(scope, id)

        self._table = aws_dynamodb.Table(
            self,
            "BackendAppStorage",
            table_name=app_config.format_resource_name(table_name),
            partition_key=aws_dynamodb.Attribute(name="PK", type=aws_dynamodb.AttributeType.STRING),
            sort_key=aws_dynamodb.Attribute(name="SK", type=aws_dynamodb.AttributeType.STRING),
            encryption=(
                aws_dynamodb.TableEncryption.CUSTOMER_MANAGED
                if encryption_key
                else aws_dynamodb.TableEncryption.AWS_MANAGED
            ),
            encryption_key=encryption_key,
            billing_mode=aws_dynamodb.BillingMode.PAY_PER_REQUEST,
            stream=aws_dynamodb.StreamViewType.NEW_AND_OLD_IMAGES if enable_streaming else None,
            point_in_time_recovery=True,
            removal_policy=(
                aws_cdk.RemovalPolicy.RETAIN
                if app_config.environment_config["retain_resources"]
                else aws_cdk.RemovalPolicy.DESTROY
            ),
            time_to_live_attribute="ExpireDate" if enable_ttl else None,
        )

        if app_config.environment_config["backup-resources"]:
            self._backup_plan = aws_backup.BackupPlan.daily_monthly1_year_retention(self, "BackendAppStorageBackUp")

            self._backup_plan.add_selection(
                "Selection", resources=[aws_backup.BackupResource.from_dynamo_db_table(self._table)]
            )

        else:
            # cdk_nag suppression
            cdk_nag.NagSuppressions.add_resource_suppressions(
                construct=self._table,
                suppressions=[
                    cdk_nag.NagPackSuppression(
                        id="NIST.800.53.R4-DynamoDBInBackupPlan",
                        reason="Lower environments don't require backup policies in place.",
                    ),
                    cdk_nag.NagPackSuppression(
                        id="NIST.800.53.R5-DynamoDBInBackupPlan",
                        reason="Lower environments don't require backup policies in place.",
                    ),
                ],
            )

        stack = aws_cdk.Stack.of(self)
        cdk_nag.NagSuppressions.add_stack_suppressions(
            stack=stack,
            suppressions=[
                cdk_nag.NagPackSuppression(
                    id="AwsSolutions-IAM4",
                    reason="AWSBackupServiceRolePolicyForBackup is enough for AWS Backup to perform DB backups",
                    applies_to=[
                        "Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup"
                    ],
                ),
                cdk_nag.NagPackSuppression(
                    id="AwsSolutions-IAM5",
                    reason="This policy is autogenerated by CDK in order to allow DynamoDB query by index. ",
                    applies_to=[
                        "Resource::<ProjectsAppStorageBackendAppStorage82ED59EB.Arn>/index/*",
                        "Resource::<ProductsAppStorageBackendAppStorageE81956C4.Arn>/index/*",
                        "Resource::<PublishingAppStorageBackendAppStorageC55862FB.Arn>/index/*",
                        "Resource::<PackagingAppStorageBackendAppStorage4DC973D8.Arn>/index/*",
                        "Resource::<ProvisioningAppStorageBackendAppStorage35BA2D33.Arn>/index/*",
                        "Resource::<ValidationVerificationAppStorageBackendAppStorage7C6A6ABE.Arn>/index/*",
                        "Resource::<NotificationsAppStorageBackendAppStorageA608F48E.Arn>/index/*",
                        "Resource::<HardwareAppStorageBackendAppStorage950F7E9A.Arn>/index/*",
                    ],
                ),
            ],
        )

    @property
    def table(self):
        return self._table

    @property
    def table_name(self):
        return self._table.table_name

    @property
    def table_arn(self):
        return self._table.table_arn
