from enum import Enum


class ProductCFStackStatus(Enum):
    """
    Please refer to following doc for cloud formation stack statuses:
    https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-describing-stacks.html#cli-stack-status-codes
    """

    UNDEFINED = "UNDEFINED"
    CREATE_COMPLETE = "CREATE_COMPLETE"
    CREATE_IN_PROGRESS = "CREATE_IN_PROGRESS"
    CREATE_FAILED = "CREATE_FAILED"
    DELETE_COMPLETE = "DELETE_COMPLETE"
    DELETE_FAILED = "DELETE_FAILED"
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS"
    REVIEW_IN_PROGRESS = "REVIEW_IN_PROGRESS"
    ROLLBACK_COMPLETE = "ROLLBACK_COMPLETE"
    ROLLBACK_FAILED = "ROLLBACK_FAILED"
    ROLLBACK_IN_PROGRESS = "ROLLBACK_IN_PROGRESS"
    UPDATE_COMPLETE = "UPDATE_COMPLETE"
    UPDATE_COMPLETE_CLEANUP_IN_PROGRESS = "UPDATE_COMPLETE_CLEANUP_IN_PROGRESS"
    UPDATE_FAILED = "UPDATE_FAILED"
    UPDATE_IN_PROGRESS = "UPDATE_IN_PROGRESS"
    UPDATE_ROLLBACK_COMPLETE = "UPDATE_ROLLBACK_COMPLETE"
    UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS = "UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS"
    UPDATE_ROLLBACK_FAILED = "UPDATE_ROLLBACK_FAILED"
    UPDATE_ROLLBACK_IN_PROGRESS = "UPDATE_ROLLBACK_IN_PROGRESS"
    IMPORT_IN_PROGRESS = "IMPORT_IN_PROGRESS"
    IMPORT_COMPLETE = "IMPORT_COMPLETE"
    IMPORT_ROLLBACK_IN_PROGRESS = "IMPORT_ROLLBACK_IN_PROGRESS"
    IMPORT_ROLLBACK_FAILED = "IMPORT_ROLLBACK_FAILED"
    IMPORT_ROLLBACK_COMPLETE = "IMPORT_ROLLBACK_COMPLETE"

    def __str__(self):
        return str(self.value)


TERMINAL_CREATE_COMPLETE_STATUSES = [
    ProductCFStackStatus.CREATE_COMPLETE,
    ProductCFStackStatus.CREATE_FAILED,
    ProductCFStackStatus.ROLLBACK_COMPLETE,
    ProductCFStackStatus.UPDATE_COMPLETE,
    ProductCFStackStatus.UPDATE_FAILED,
    ProductCFStackStatus.UPDATE_ROLLBACK_COMPLETE,
    ProductCFStackStatus.UPDATE_ROLLBACK_FAILED,
    ProductCFStackStatus.UPDATE_IN_PROGRESS,
]
